//
//  DataTestConstanst.swift
//  MercadoPruebaTests
//
//  Created by iMac on 25/03/24.
//

import Foundation
@testable import MercadoPrueba
struct DataTestConstants {
    
    
    static let apiProductsObject:[ProductObject] = [
    
        .init(id: "0",
              title: "Xbox series s",
              condition: "new",
              thumbnail_id: "124343",
              listing_type_id: "hdrgsf",
              permalink: "https://www.mercadolibre.com.co/consola-xbox-series-s-standard-512gb-color-blanco/p/MCO16650345",
              buying_mode: "",
              site_id: "",
              category_id: "sd",
              domain_id: "co",
              thumbnail: "https://estaticos.elcolombiano.com/binrepository/960x621/0c0/0d0/none/11101/JNIE/europapress-2289065-xbox-one-all-digital_42611007_20230616063943.jpg",
              currency_id: "",
              order_backend: 0,
              price: 1300000,
              available_quantity: 0,
              use_thumbnail_id: true,
              accepts_mercadopago: true),
        
            .init(id: "1",
                  title: "Xbox series x",
                  condition: "new",
                  thumbnail_id: "124343",
                  listing_type_id: "hdrgsf",
                  permalink: "https://www.mercadolibre.com.co/consola-microsoft-xbox-series-x-standard-1tb-color-negro/p/MCO16160759",
                  buying_mode: "",
                  site_id: "",
                  category_id: "sd",
                  domain_id: "co",
                  thumbnail: "https://news.xbox.com/es-latam/wp-content/uploads/sites/4/2020/09/XSX_XSS_Design_HERO.jpg",
                  currency_id: "",
                  order_backend: 0,
                  price: 2300000,
                  available_quantity: 0,
                  use_thumbnail_id: true,
                  accepts_mercadopago: true),
        
            .init(id: "2",
                  title: "Xbox series x",
                  condition: "new",
                  thumbnail_id: "124343",
                  listing_type_id: "hdrgsf",
                  permalink: "https://www.mercadolibre.com.co/consola-microsoft-xbox-series-x-standard-1tb-color-negro/p/MCO16160759",
                  buying_mode: "",
                  site_id: "",
                  category_id: "sd",
                  domain_id: "co",
                  thumbnail: "https://news.xbox.com/es-latam/wp-content/uploads/sites/4/2020/09/XSX_XSS_Design_HERO.jpg",
                  currency_id: "",
                  order_backend: 0,
                  price: 2300000,
                  available_quantity: 0,
                  use_thumbnail_id: true,
                  accepts_mercadopago: true),
        
            .init(id: "3",
                  title: "Xbox series s",
                  condition: "new",
                  thumbnail_id: "124343",
                  listing_type_id: "hdrgsf",
                  permalink: "https://www.mercadolibre.com.co/consola-xbox-series-s-standard-512gb-color-blanco/p/MCO16650345",
                  buying_mode: "",
                  site_id: "",
                  category_id: "sd",
                  domain_id: "co",
                  thumbnail: "https://estaticos.elcolombiano.com/binrepository/960x621/0c0/0d0/none/11101/JNIE/europapress-2289065-xbox-one-all-digital_42611007_20230616063943.jpg",
                  currency_id: "",
                  order_backend: 0,
                  price: 1300000,
                  available_quantity: 0,
                  use_thumbnail_id: true,
                  accepts_mercadopago: true),
        
            .init(id: "4",
                  title: "Xbox series s",
                  condition: "new",
                  thumbnail_id: "124343",
                  listing_type_id: "hdrgsf",
                  permalink: "https://www.mercadolibre.com.co/consola-xbox-series-s-standard-512gb-color-blanco/p/MCO16650345",
                  buying_mode: "",
                  site_id: "",
                  category_id: "sd",
                  domain_id: "co",
                  thumbnail: "https://estaticos.elcolombiano.com/binrepository/960x621/0c0/0d0/none/11101/JNIE/europapress-2289065-xbox-one-all-digital_42611007_20230616063943.jpg",
                  currency_id: "",
                  order_backend: 0,
                  price: 1300000,
                  available_quantity: 0,
                  use_thumbnail_id: true,
                  accepts_mercadopago: true)
        
    
    
    ]
    
    static let apiProductsObjectResponse:[APIProductObject] = [
    
        .init(id: "0",
              title: "Xbox series s",
              condition: "new",
              thumbnail_id: "124343",
              listing_type_id: "hdrgsf",
              permalink: "https://www.mercadolibre.com.co/consola-xbox-series-s-standard-512gb-color-blanco/p/MCO16650345",
              buying_mode: "",
              site_id: "",
              category_id: "sd",
              domain_id: "co",
              thumbnail: "https://estaticos.elcolombiano.com/binrepository/960x621/0c0/0d0/none/11101/JNIE/europapress-2289065-xbox-one-all-digital_42611007_20230616063943.jpg",
              currency_id: "",
              order_backend: 0,
              price: 1300000,
              available_quantity: 0,
              use_thumbnail_id: true,
              accepts_mercadopago: true),
        
            .init(id: "1",
                  title: "Xbox series x",
                  condition: "new",
                  thumbnail_id: "124343",
                  listing_type_id: "hdrgsf",
                  permalink: "https://www.mercadolibre.com.co/consola-microsoft-xbox-series-x-standard-1tb-color-negro/p/MCO16160759",
                  buying_mode: "",
                  site_id: "",
                  category_id: "sd",
                  domain_id: "co",
                  thumbnail: "https://news.xbox.com/es-latam/wp-content/uploads/sites/4/2020/09/XSX_XSS_Design_HERO.jpg",
                  currency_id: "",
                  order_backend: 0,
                  price: 2300000,
                  available_quantity: 0,
                  use_thumbnail_id: true,
                  accepts_mercadopago: true),
        
            .init(id: "2",
                  title: "Xbox series x",
                  condition: "new",
                  thumbnail_id: "124343",
                  listing_type_id: "hdrgsf",
                  permalink: "https://www.mercadolibre.com.co/consola-microsoft-xbox-series-x-standard-1tb-color-negro/p/MCO16160759",
                  buying_mode: "",
                  site_id: "",
                  category_id: "sd",
                  domain_id: "co",
                  thumbnail: "https://news.xbox.com/es-latam/wp-content/uploads/sites/4/2020/09/XSX_XSS_Design_HERO.jpg",
                  currency_id: "",
                  order_backend: 0,
                  price: 2300000,
                  available_quantity: 0,
                  use_thumbnail_id: true,
                  accepts_mercadopago: true),
        
            .init(id: "3",
                  title: "Xbox series s",
                  condition: "new",
                  thumbnail_id: "124343",
                  listing_type_id: "hdrgsf",
                  permalink: "https://www.mercadolibre.com.co/consola-xbox-series-s-standard-512gb-color-blanco/p/MCO16650345",
                  buying_mode: "",
                  site_id: "",
                  category_id: "sd",
                  domain_id: "co",
                  thumbnail: "https://estaticos.elcolombiano.com/binrepository/960x621/0c0/0d0/none/11101/JNIE/europapress-2289065-xbox-one-all-digital_42611007_20230616063943.jpg",
                  currency_id: "",
                  order_backend: 0,
                  price: 1300000,
                  available_quantity: 0,
                  use_thumbnail_id: true,
                  accepts_mercadopago: true),
        
            .init(id: "4",
                  title: "Xbox series s",
                  condition: "new",
                  thumbnail_id: "124343",
                  listing_type_id: "hdrgsf",
                  permalink: "https://www.mercadolibre.com.co/consola-xbox-series-s-standard-512gb-color-blanco/p/MCO16650345",
                  buying_mode: "",
                  site_id: "",
                  category_id: "sd",
                  domain_id: "co",
                  thumbnail: "https://estaticos.elcolombiano.com/binrepository/960x621/0c0/0d0/none/11101/JNIE/europapress-2289065-xbox-one-all-digital_42611007_20230616063943.jpg",
                  currency_id: "",
                  order_backend: 0,
                  price: 1300000,
                  available_quantity: 0,
                  use_thumbnail_id: true,
                  accepts_mercadopago: true)
        
    
    
    ]
    
    static let productObject:ProductObject = ProductObject(id: "4",
                                                           title: "Xbox series s",
                                                           condition: "new",
                                                           thumbnail_id: "124343",
                                                           listing_type_id: "hdrgsf",
                                                           permalink: "https://www.mercadolibre.com.co/consola-xbox-series-s-standard-512gb-color-blanco/p/MCO16650345",
                                                           buying_mode: "",
                                                           site_id: "",
                                                           category_id: "sd",
                                                           domain_id: "co",
                                                           thumbnail: "https://estaticos.elcolombiano.com/binrepository/960x621/0c0/0d0/none/11101/JNIE/europapress-2289065-xbox-one-all-digital_42611007_20230616063943.jpg",
                                                           currency_id: "",
                                                           order_backend: 0,
                                                           price: 1300000,
                                                           available_quantity: 0,
                                                           use_thumbnail_id: true,
                                                           accepts_mercadopago: true)
}
